# -*- coding: utf-8 -*-
"""AI_Resume_Matcher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ASFTpuEdas4Zimm9iKJxmeowk_OBb0r5
"""


import streamlit as st
import os
import PyPDF2
import docx2txt
import gradio as gr
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# 1. Function to extract text
def extract_text(file_obj):
    file_path = file_obj.name
    if file_path.endswith('.pdf'):
        text = ""
        with open(file_path, 'rb') as f:
            reader = PyPDF2.PdfReader(f)
            for page in reader.pages:
                text += page.extract_text()
        return text
    elif file_path.endswith('.docx'):
        return docx2txt.process(file_path)
    elif file_path.endswith('.txt'):
        with open(file_path, 'r', encoding='utf-8') as f:
            return f.read()
    return ""

# 2. The Core AI Matcher Function
def resume_matcher(job_description, resumes):
    if not resumes or not job_description:
        return "Please upload resumes and provide a Job Description."

    resumes_text = []
    resume_names = []

    for file in resumes:
        text = extract_text(file)
        if text:
            resumes_text.append(text)
            resume_names.append(os.path.basename(file.name))

    # Vectorization (The Efficiency Logic we discussed)
    all_content = [job_description] + resumes_text
    vectorizer = TfidfVectorizer(stop_words='english', ngram_range=(1, 2))
    vectors = vectorizer.fit_transform(all_content).toarray()

    job_vector = vectors[0].reshape(1, -1)
    resume_vectors = vectors[1:]

    similarities = cosine_similarity(job_vector, resume_vectors).flatten()

    # Format the output for the interface
    results = []
    for i in range(len(resume_names)):
        score = round(similarities[i] * 100, 2)
        results.append({"Candidate": resume_names[i], "Match Score (%)": score})

    # Sort results by highest score
    results = sorted(results, key=lambda x: x['Match Score (%)'], reverse=True)
    return results

# 3. Create the Gradio Interface
interface = gr.Interface(
    fn=resume_matcher,
    inputs=[
        gr.Textbox(lines=7, label="Paste Job Description Here"),
        gr.File(file_count="multiple", label="Upload Resumes (PDF, Docx, TXT)")
    ],
    outputs=gr.JSON(label="Ranked Matches"),
    title="AI Resume Screening Automation",
    description="Upload multiple resumes to see how well they match the Job Description based on TF-IDF Similarity."
)

# Launch it!
interface.launch(debug=True)
